services:
  nats:
    image: nats:latest
    container_name: nats-server
    restart: unless-stopped
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
      # - "6222:6222"  # Cluster port (if clustering is needed)
    command: "--user ${NATS_USER} --pass ${NATS_PASSWORD} -js"  # Optional authentication
    volumes:
      - ./nats-data:/var/lib/nats  # Persistent storage for messages (if needed)
    networks:
      - solvexity-net

  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3

networks:
  solvexity-net:
    driver: bridge