services:
  nats:
    image: nats:latest
    container_name: nats-server
    restart: unless-stopped
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
      # - "6222:6222"  # Cluster port (if clustering is needed)
    # command: "--user myuser --pass mypass"  # Optional authentication
    command: "-js"  # Enable JetStream
    volumes:
      - ./nats-data:/var/lib/nats  # Persistent storage for messages (if needed)
    networks:
      - solvexity-net

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    networks:
      - solvexity-net

networks:
  solvexity-net:
    driver: bridge