services:
  nats:
    image: nats:latest
    container_name: nats-server
    restart: unless-stopped
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
      # - "6222:6222"  # Cluster port (if clustering is needed)
    # command: "--user myuser --pass mypass"  # Optional authentication
    volumes:
      - ./nats-data:/var/lib/nats  # Persistent storage for messages (if needed)
    networks:
      - solvexity-net

  redis:
    image: redis/redis-stack:latest
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web UI
    volumes:
      - ./redis-data:/data
    networks:
      - solvexity-net

networks:
  solvexity-net:
    driver: bridge