services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  logger:
    image: ghcr.io/bullionbear/solvexity:latest
    container_name: logger
    environment:
      PYTHONPATH: /solvexity
    volumes:
      - ../log:/var/log/
      - ../.env:/solvexity/.env
    pull_policy: always
    command: [ "python", "infra/log_aggregator.py", "--log-dir", "/var/log/", "--redis-host", "redis", "--redis-port", "6379", "--channel", "log_channel", "--system", "test", "--notify", "notifydev" ]

volumes:
  redis_data:
