nodes:
  - name: binance_public_trade_feed_btc_usdt
    type: trade_feed
    config:
      exchange: binance
      symbol:
        - base_currency: BTC
          quote_currency: USDT
          instrument_type: spot
      credentials:
        api_key: ""
        api_secret: ""