app:
  host: "0.0.0.0"
  port: 8000

deployer:
  pilot:
    type: "nats"
    url:
      - "nats://localhost:4222"
    user: ${NATS_USER}
    password: ${NATS_PASSWORD}
  nodes:
    - type: "TradeFeed"
      config:
        node_id: "emit.trade.binance.btc.usdt.spot"
        exchange: BINANCE
        symbol: BTC-USDT-SPOT
        
