app:
  host: "0.0.0.0"
  port: 8000

deployer:
  pilot:
    type: "nats"
    url: "nats://localhost:4222"
  nodes:
    - type: "TradeFeed"
      config:
        exchange: "BINANCE"
        symbol:
          base_currency: BTC
          quote_currency: USDT
          instrument_type: SPOT
        node_id: "trade_feed_1"
        use_testnet: false

