app:
  host: "0.0.0.0"
  port: 8000

logger:
  level: "INFO"
  format_type: "detailed"
  log_file: "logs/emit_binance_btc_usdt_spot.log"
  rotation: true
  max_backup: 5

deployer:
  pilot:
    type: "nats"
    urls:
      - "nats://localhost:4222"
    options:
      user: ${NATS_USER}
      password: ${NATS_PASS}
  nodes:
    - type: "TradeFeed"
      config:
        node_id: "emit.binance.btc.usdt.spot"
        exchange: BINANCE
        symbol: BTC-USDT-SPOT
        
