app:
  host: "0.0.0.0"
  port: 8002

deployer:
  pilot:
    type: "nats"
    urls:
      - "nats://localhost:4222"
    options:
      user: ${NATS_USER}
      password: ${NATS_PASS}
  nodes:
    - type: "InfluxWriteWorker"
      config:
        node_id: "worker.influx"
        influxdb_url: "${INFLUXDB_URL}"
        influxdb_token: "${INFLUXDB_TOKEN}"
        influxdb_database: "${INFLUXDB_DATABASE}"

