app:
  host: "0.0.0.0"
  port: 8001

deployer:
  pilot:
    type: "nats"
    urls:
      - "nats://localhost:4222"
    options:
      user: ${NATS_USER}
      password: ${NATS_PASS}
  nodes:
    - type: "JobDispatcher"
      config:
        node_id: "sink.influx"
        subscribes:
          - "emit.binance.btc.usdt.spot.trade"
        dispatch_to: "worker.influx"
