app:
  host: "0.0.0.0"
  port: 9999

deployer:
  pilot:
    type: "nats"
    urls:
      - "nats://localhost:4222"
    options:
      user: ${NATS_USER}
      password: ${NATS_PASS}
  nodes:
    - type: "DebugNode"
      config:
        node_id: "debug"
        subscribes:
          - "emit.binance.btc.usdt.spot.trade"
