app:
  host: "0.0.0.0"
  port: 8002

logger:
  solvexity:
    level: "INFO"
    format_type: "detailed"
    log_file: "logs/worker_influx_node.log"
    rotation: true
    max_backup: 5
  uvicorn:
    level: "INFO"
    log_file: "logs/worker_influx_uvicorn.log"
    rotation: true
    max_backup: 5

deployer:
  pilot:
    type: "nats"
    urls:
      - "nats://localhost:4222"
    options:
      user: ${NATS_USER}
      password: ${NATS_PASS}
  nodes:
    - type: "InfluxWriteWorker"
      config:
        node_id: "worker.influx"
        influxdb_url: "${INFLUXDB_URL}"
        influxdb_token: "${INFLUXDB_TOKEN}"
        influxdb_database: "${INFLUXDB_DATABASE}"
        max_batch_size: 1000
        flush_interval_ms: 5000

