class ERROR:
    CMD_INVALID_INPUT = "CMD_INVALID_INPUT"
    CMD_NOT_FOUND = "CMD_NOT_FOUND"
    CMD_NOT_IMPLEMENTED = "CMD_NOT_IMPLEMENTED"

class TRADE_METHOD:
    HEALTH_CHECK = "HEALTH_CHECK"
    CONFIG_NAME = "CONFIG_NAME"

class FEED_METHOD:
    HEALTH_CHECK = "HEALTH_CHECK"
    CONFIG_NAME = "CONFIG_NAME"