# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/shared.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobuf/shared.proto\x12\x03\x61pp\"%\n\x06Symbol\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\t\x12\r\n\x05quote\x18\x02 \x01(\t*\xb0\x01\n\nInstrument\x12\x1a\n\x16INSTRUMENT_UNSPECIFIED\x10\x00\x12\x13\n\x0fINSTRUMENT_SPOT\x10\x01\x12\x15\n\x11INSTRUMENT_MARGIN\x10\x02\x12\x13\n\x0fINSTRUMENT_PERP\x10\x03\x12\x16\n\x12INSTRUMENT_INVERSE\x10\x04\x12\x16\n\x12INSTRUMENT_FUTURES\x10\x05\x12\x15\n\x11INSTRUMENT_OPTION\x10\x06*i\n\x08\x45xchange\x12\x18\n\x14\x45XCHANGE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x45XCHANGE_BINANCE\x10\x01\x12\x19\n\x15\x45XCHANGE_BINANCE_PERP\x10\x02\x12\x12\n\x0e\x45XCHANGE_BYBIT\x10\x03*9\n\x04Side\x12\x14\n\x10SIDE_UNSPECIFIED\x10\x00\x12\x0c\n\x08SIDE_BUY\x10\x01\x12\r\n\tSIDE_SELL\x10\x02*q\n\x0bTimeInForce\x12\x1d\n\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n\x11TIME_IN_FORCE_FOK\x10\x03*p\n\tOrderType\x12\x1a\n\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n\x11ORDER_TYPE_MARKET\x10\x02\x12\x1a\n\x16ORDER_TYPE_STOP_MARKET\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.shared_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRUMENT._serialized_start=70
  _INSTRUMENT._serialized_end=246
  _EXCHANGE._serialized_start=248
  _EXCHANGE._serialized_end=353
  _SIDE._serialized_start=355
  _SIDE._serialized_end=412
  _TIMEINFORCE._serialized_start=414
  _TIMEINFORCE._serialized_end=527
  _ORDERTYPE._serialized_start=529
  _ORDERTYPE._serialized_end=641
  _SYMBOL._serialized_start=30
  _SYMBOL._serialized_end=67
# @@protoc_insertion_point(module_scope)
