# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/trade.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as protobuf_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protobuf/trade.proto\x12\x03\x61pp\x1a\x15protobuf/shared.proto\"\xc3\x01\n\x05Trade\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1f\n\x08\x65xchange\x18\x02 \x01(\x0e\x32\r.app.Exchange\x12#\n\ninstrument\x18\x03 \x01(\x0e\x32\x0f.app.Instrument\x12\x1b\n\x06symbol\x18\x04 \x01(\x0b\x32\x0b.app.Symbol\x12\x17\n\x04side\x18\x05 \x01(\x0e\x32\t.app.Side\x12\r\n\x05price\x18\x07 \x01(\x01\x12\x10\n\x08quantity\x18\x08 \x01(\x01\x12\x11\n\ttimestamp\x18\t \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.trade_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRADE._serialized_start=53
  _TRADE._serialized_end=248
# @@protoc_insertion_point(module_scope)
